/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCYLEONOR
 */
public class Fotos extends javax.swing.JFrame {

    /**
     * Creates new form Fotos
     */
    public Fotos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fotos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Fotos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Núm. Fotos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFKeyTyped(evt);
            }
        });
        jPanel1.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Total a Pagar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 30));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        cmdRestaurar.setText("Restaurar");
        cmdRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        if (txtF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De Fotos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtF.requestFocusInWindow();

        } else if (txtF.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "El Número De Fotos Debe Ser Superior 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtF.requestFocusInWindow();
            txtF.selectAll();
        } else {

            String r;
            double f, t;

            f = Double.parseDouble(txtF.getText());

            t = (f * 1500) * 1.16;

            r = String.valueOf(t);
            lblT.setText("$ " + r);
        }

        
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaurarActionPerformed

        txtF.setText("");
        lblT.setText("");
        txtF.requestFocusInWindow();
        
    }//GEN-LAST:event_cmdRestaurarActionPerformed

    private void txtFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado El Numero De Fotos", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtF.requestFocusInWindow();

            } else if (txtF.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "El Número De Fotos Debe Ser Superior 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtF.requestFocusInWindow();
                txtF.selectAll();
            } else {

                String r;
                double f, t;

                f = Double.parseDouble(txtF.getText());

                t = (f * 1500) * 1.16;

                r = String.valueOf(t);
                lblT.setText("$ " + r);
            }

        }
        
    }//GEN-LAST:event_txtFKeyPressed

    private void txtFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblT;
    private javax.swing.JTextField txtF;
    // End of variables declaration//GEN-END:variables
}
